### ISSUE TITLE
feature : indicate the word has a glossary entry

### ISSUE THREAD

**Issue by Ciflire** [ENIB-Community/glossarium#2]
Hi i was looking for a way to indicate that the word has an entry in the glossary. There are many ways to do it, like a little star, but i have been recommended by my friend to add a numeration like [1] [2] on the right and you could also add it just before the `short` argument

**Comment by slashformotion** [comment]
here is the way i achieve it. i use `#show link: set text(fill: blue.darken(60%))` to set the link color to blue.

looks like this 
![image](https://github.com/ENIB-Community/glossarium/assets/45801817/9322ab8c-c724-4d1f-920b-8e76cda3d7ee)

It's quite intuitive because it is look similar to links on the web.

**Comment by slashformotion** [comment]
reopen if not fixed
